spring:
  emily:
    redis:
      enabled: true
      config:
        default:
          # 客户端连接类型
          client-type: lettuce
          database: 15
          password: test12345
          sentinel:
            master: mymaster
            nodes: 10.10.84.156:26380,10.10.84.157:26381,10.10.84.158:26382
          timeout: 300
          lettuce:
            pool:
              # 最大活跃连接数，-1表示无穷大
              max-active: 8
              # 最大空闲连接数
              max-idle: 8
              # 最小空闲连接数
              min-idle: 0
              # 连接池耗尽最长等待时间，-1无限期阻止
              max-wait: -1
        test:
          # 默认lettuce模式，
          client-type: lettuce
          database: 15
          password: Emis_Qaz123
          sentinel:
            master: mymaster
            nodes: 10.10.181.41:26379,10.10.181.42:26379,10.10.181.43:26379
          timeout: 300
          lettuce:
            pool:
              # 最大活跃连接数，-1表示无穷大
              max-active: 8
              # 最大空闲连接数
              max-idle: 8
              # 最小空闲连接数
              min-idle: 0
              # 连接池耗尽最长等待时间，-1无限期阻止
              max-wait: -1
        one:
          # 客户端连接类型
          client-type: lettuce
          # 服务IP地址
          host: 172.30.67.122
          # 端口号
          port: 6379
          # 用户名
          username:
          # 密码
          password: admin
          # 读取超时时间
          timeout: PT3S
          # 连接超时时间
          connect-timeout: PT3S
          # 基于netty的线程池
          lettuce:
            pool:
              # 连接池最大连接数（使用复值标识没有限制），默认：8
              max-active: 8
              # 连接池中的最大空闲连接
              max-idle: 8
              # 连接池中的最小空闲连接， 默认：0
              min-idle: 0
              # 连接阻塞的最长时间（也就是多长时间之后会抛出异常），默认：-1 无限阻塞
              max-wait: -1ms
              # 空闲对象逐出器线程的运行间隔时间，为正值时，空闲逐出器线程启动，否则不执行空闲对象逐出
              time-between-eviction-runs: PT0.1S